disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - cyclomatic_complexity
  - type_name
  - type_body_length
  - nesting
  - force_cast
  - force_try

line_length: 225
function_body_length:
  warning: 150
  error: 200
file_length:
  warning: 500
  error: 700
function_parameter_count:
  warning: 10
  error: 15
