name: Build and test

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install linter
      run: brew link --overwrite swiftlint || brew install swiftlint
    - name: Run linter
      run: swiftlint
